import { Metadata } from "next";
import dynamic from "next/dynamic";

const AboutSectionOne = dynamic(
  () => import("@/components/About/AboutSectionOne"),
);
const AboutSectionTwo = dynamic(
  () => import("@/components/About/AboutSectionTwo"),
);
const Blog = dynamic(() => import("@/components/Blog"));
const Brands = dynamic(() => import("@/components/Brands"));
const Contact = dynamic(() => import("@/components/Contact"));
const Features = dynamic(() => import("@/components/Services"));
const Hero = dynamic(() => import("@/components/Hero"));
const Pricing = dynamic(() => import("@/components/Pricing"));
const Testimonials = dynamic(() => import("@/components/Testimonials"));
const Video = dynamic(() => import("@/components/Video"));
const ScrollUp = dynamic(() => import("@/components/Common/ScrollUp"));

const homeMetada = {
  url: "https://technosive.co.uk",
  title: "Technosive | Your Cybersecurity Partner",
  description:
    "Technosive: Your trusted cybersecurity partner providing comprehensive protection, security, defense, and compliance solutions for your digital infrastructure.",
  imgUrl: "https://technosive.co.uk/images/logo/TechnosiveOG.webp",
  imgAltText: "Technosive Cybersecurity",
  keywords: [
    "Cybersecurity",
    "Security",
    "Protection",
    "Defense",
    "Compliance",
    "Technosive",
    "Digital Security",
    "Threat Protection",
    "Security Solutions",
    "Cyber Defense",
    "Information Security",
    "Network Security",
    "Data Protection",
    "Security Consulting",
    "Risk Management",
    "Security Audits",
    "Penetration Testing",
    "Security Monitoring",
    "Incident Response",
    "Security Assessment",
    "Vulnerability Management",
    "Security Architecture",
    "Compliance Management",
    "Security Operations",
    "Threat Intelligence",
    "Security Awareness",
    "Cyber Risk",
    "Security Strategy",
    "Security Implementation",
    "Security Optimization",
    "Security Maintenance",
    "Security Support",
    "Security Training",
    "Security Certification",
    "Security Standards",
    "Security Best Practices",
    "Security Policies",
    "Security Procedures",
    "Security Guidelines",
    "Security Frameworks",
    "Security Controls",
    "Security Measures",
    "Security Protocols",
    "Security Technologies",
    "Security Tools",
    "Security Platforms",
    "Security Systems",
    "Security Infrastructure",
    "Security Services",
    "Security Solutions",
    "Security Expertise",
    "Security Experience",
    "Security Knowledge",
    "Security Skills",
    "Security Capabilities",
    "Security Resources",
    "Security Partners",
    "Security Providers",
    "Security Vendors",
    "Security Consultants",
    "Security Specialists",
    "Security Experts",
    "Security Professionals",
    "Security Engineers",
    "Security Analysts",
    "Security Architects",
    "Security Managers",
    "Security Directors",
    "Security Officers",
    "Security Executives",
    "Security Leaders",
    "Security Teams",
    "Security Organizations",
    "Security Companies",
    "Security Agencies",
    "Security Authorities",
    "Security Regulators",
    "Security Standards Bodies",
    "Security Associations",
    "Security Communities",
    "Security Groups",
    "Security Forums",
    "Security Conferences",
    "Security Events",
    "Security Training",
    "Security Education",
    "Security Certification",
    "Security Accreditation",
    "Security Recognition",
    "Security Awards",
    "Security Achievements",
    "Security Success",
    "Security Excellence",
    "Security Innovation",
    "Security Leadership",
    "Security Vision",
    "Security Mission",
    "Security Goals",
    "Security Objectives",
    "Security Targets",
    "Security Outcomes",
    "Security Results",
    "Security Benefits",
    "Security Value",
    "Security ROI",
    "Security Investment",
    "Security Budget",
    "Security Funding",
    "Security Resources",
    "Security Assets",
    "Security Capabilities",
    "Security Strengths",
    "Security Advantages",
    "Security Differentiators",
    "Security Competitors",
    "Security Market",
    "Security Industry",
    "Security Sector",
    "Security Domain",
    "Security Field",
    "Security Area",
    "Security Specialty",
    "Security Focus",
    "Security Niche",
    "Security Segment",
    "Security Category",
    "Security Classification",
    "Security Type",
    "Security Kind",
    "Security Variety",
    "Security Sort",
    "Security Class",
    "Security Group",
    "Security Division",
    "Security Department",
    "Security Unit",
    "Security Team",
    "Security Crew",
    "Security Staff",
    "Security Personnel",
    "Security Workforce",
    "Security Talent",
    "Security Experts",
    "Security Specialists",
    "Security Professionals",
    "Security Practitioners",
    "Security Consultants",
    "Security Advisors",
    "Security Counselors",
    "Security Guides",
    "Security Mentors",
    "Security Coaches",
    "Security Trainers",
    "Security Educators",
    "Security Instructors",
    "Security Teachers",
    "Security Professors",
    "Security Researchers",
    "Security Scientists",
    "Security Scholars",
    "Security Authors",
    "Security Writers",
    "Security Speakers",
    "Security Presenters",
    "Security Panelists",
    "Security Moderators",
    "Security Facilitators",
    "Security Coordinators",
    "Security Organizers",
    "Security Planners",
    "Security Strategists",
    "Security Tacticians",
    "Security Operators",
    "Security Technicians",
    "Security Engineers",
    "Security Developers",
    "Security Programmers",
    "Security Coders",
    "Security Builders",
    "Security Creators",
    "Security Designers",
    "Security Architects",
    "Security Planners",
    "Security Designers",
    "Security Developers",
    "Security Implementers",
    "Security Deployers",
    "Security Installers",
    "Security Configurators",
    "Security Administrators",
    "Security Operators",
    "Security Maintainers",
    "Security Supporters",
    "Security Helpers",
    "Security Assistants",
    "Security Aides",
    "Security Technicians",
    "Security Specialists",
    "Security Experts",
    "Security Authorities",
    "Security Leaders",
    "Security Managers",
    "Security Directors",
    "Security Executives",
    "Security Officers",
    "Security Chiefs",
    "Security Heads",
    "Security Bosses",
    "Security Supervisors",
    "Security Overseers",
    "Security Controllers",
    "Security Commanders",
    "Security Captains",
    "Security Lieutenants",
    "Security Sergeants",
    "Security Officers",
    "Security Agents",
    "Security Representatives",
    "Security Delegates",
    "Security Ambassadors",
    "Security Advocates",
    "Security Champions",
    "Security Supporters",
    "Security Promoters",
    "Security Endorsers",
    "Security Backers",
    "Security Sponsors",
    "Security Patrons",
    "Security Benefactors",
    "Security Donors",
    "Security Contributors",
    "Security Participants",
    "Security Members",
    "Security Partners",
    "Security Collaborators",
    "Security Cooperators",
    "Security Teammates",
    "Security Colleagues",
    "Security Peers",
    "Security Associates",
    "Security Allies",
    "Security Friends",
    "Security Companions",
    "Security Mates",
    "Security Buddies",
    "Security Pals",
    "Security Chums",
    "Security Friends",
    "Security Acquaintances",
    "Security Contacts",
    "Security Connections",
    "Security Links",
    "Security Relations",
    "Security Relationships",
    "Security Bonds",
    "Security Ties",
    "Security Affiliations",
    "Security Associations",
    "Security Memberships",
    "Security Subscriptions",
    "Security Registrations",
    "Security Enrollments",
    "Security Signups",
    "Security Joinings",
    "Security Participations",
    "Security Involvements",
    "Security Engagements",
    "Security Commitments",
    "Security Dedication",
    "Security Loyalty",
    "Security Fidelity",
    "Security Faithfulness",
    "Security Devotion",
    "Security Allegiance",
    "Security Adherence",
    "Security Obedience",
    "Security Compliance",
    "Security Conformity",
    "Security Observance",
    "Security Following",
    "Security Adherence",
    "Security Sticking",
    "Security Abiding",
    "Security Complying",
    "Security Conforming",
    "Security Observing",
    "Security Heeding",
    "Security Minding",
    "Security Attending",
    "Security Regarding",
    "Security Noting",
    "Security Noticing",
    "Security Detecting",
    "Security Spotting",
    "Security Identifying",
    "Security Recognizing",
    "Security Discerning",
    "Security Perceiving",
    "Security Realizing",
    "Security Understanding",
    "Security Comprehending",
    "Security Grasping",
    "Security Fathoming",
    "Security Mastering",
    "Security Learning",
    "Security Studying",
    "Security Researching",
    "Security Investigating",
    "Security Examining",
    "Security Analyzing",
    "Security Evaluating",
    "Security Assessing",
    "Security Appraising",
    "Security Judging",
    "Security Determining",
    "Security Deciding",
    "Security Concluding",
    "Security Resolving",
    "Security Solving",
    "Security Fixing",
    "Security Repairing",
    "Security Restoring",
    "Security Recovering",
    "Security Retrieving",
    "Security Regaining",
    "Security Reclaiming",
    "Security Recapturing",
    "Security Reacquiring",
    "Security Reobtaining",
    "Security Regaining",
    "Security Recovering",
    "Security Restoring",
    "Security Reinstating",
    "Security Reestablishing",
    "Security Rebuilding",
    "Security Renovating",
    "Security Revamping",
    "Security Revitalizing",
    "Security Rejuvenating",
    "Security Refreshing",
    "Security Renewing",
    "Security Restarting",
    "Security Relaunching",
    "Security Reinitiating",
    "Security Recommencing",
    "Security Resuming",
    "Security Continuing",
    "Security Proceeding",
    "Security Moving",
    "Security Advancing",
    "Security Progressing",
    "Security Developing",
    "Security Evolving",
    "Security Growing",
    "Security Expanding",
    "Security Extending",
    "Security Stretching",
    "Security Broadening",
    "Security Widening",
    "Security Enlarging",
    "Security Magnifying",
    "Security Amplifying",
    "Security Boosting",
    "Security Enhancing",
    "Security Improving",
    "Security Upgrading",
    "Security Elevating",
    "Security Raising",
    "Security Lifting",
    "Security Increasing",
    "Security Growing",
    "Security Building",
    "Security Constructing",
    "Security Creating",
    "Security Making",
    "Security Producing",
    "Security Generating",
    "Security Forming",
    "Security Shaping",
    "Security Molding",
    "Security Fashioning",
    "Security Crafting",
    "Security Building",
    "Security Assembling",
    "Security Putting",
    "Security Setting",
    "Security Placing",
    "Security Positioning",
    "Security Locating",
    "Security Situating",
    "Security Establishing",
    "Security Founding",
    "Security Instituting",
    "Security Creating",
    "Security Forming",
    "Security Organizing",
    "Security Structuring",
    "Security Arranging",
    "Security Ordering",
    "Security Sorting",
    "Security Classifying",
    "Security Categorizing",
    "Security Grouping",
    "Security Bunching",
    "Security Clustering",
    "Security Collecting",
    "Security Gathering",
    "Security Accumulating",
    "Security Amassing",
    "Security Assembling",
    "Security Compiling",
    "Security Composing",
    "Security Constituting",
    "Security Comprising",
    "Security Embodying",
    "Security Incorporating",
    "Security Integrating",
    "Security Merging",
    "Security Combining",
    "Security Joining",
    "Security Uniting",
    "Security Connecting",
    "Security Linking",
    "Security Attaching",
    "Security Fastening",
    "Security Fixing",
    "Security Securing",
    "Safety",
    "Protection",
    "Defense",
    "Guardianship",
    "Custody",
    "Care",
    "Custodianship",
    "Keeping",
    "Safekeeping",
    "Preservation",
    "Conservation",
    "Maintenance",
    "Upkeep",
    "Support",
    "Backing",
    "Endorsement",
    "Approval",
    "Sanction",
    "Authorization",
    "Permission",
    "Consent",
    "Agreement",
    "Acceptance",
    "Assent",
    "Endorsement",
    "Backing",
    "Support",
    "Help",
    "Assistance",
    "Aid",
    "Relief",
    "Service",
    "Contribution",
    "Input",
    "Participation",
    "Involvement",
    "Engagement",
    "Commitment",
    "Dedication",
    "Loyalty",
    "Fidelity",
    "Faithfulness",
    "Devotion",
    "Allegiance",
    "Adherence",
    "Obedience",
    "Compliance",
    "Conformity",
    "Observance",
    "Following",
    "Adherence",
    "Sticking",
    "Abiding",
    "Complying",
    "Conforming",
    "Observing",
    "Heeding",
    "Minding",
    "Attending",
    "Regarding",
    "Noting",
    "Noticing",
    "Detecting",
    "Spotting",
    "Identifying",
    "Recognizing",
    "Discerning",
    "Perceiving",
    "Realizing",
    "Understanding",
    "Comprehending",
    "Grasping",
    "Fathoming",
    "Mastering",
    "Learning",
    "Studying",
    "Researching",
    "Investigating",
    "Examining",
    "Analyzing",
    "Evaluating",
    "Assessing",
    "Appraising",
    "Judging",
    "Determining",
    "Deciding",
    "Concluding",
    "Resolving",
    "Solving",
    "Fixing",
    "Repairing",
    "Restoring",
    "Recovering",
    "Retrieving",
    "Regaining",
    "Reclaiming",
    "Recapturing",
    "Reacquiring",
    "Reobtaining",
    "Regaining",
    "Recovering",
    "Restoring",
    "Reinstating",
    "Reestablishing",
    "Rebuilding",
    "Renovating",
    "Revamping",
    "Revitalizing",
    "Rejuvenating",
    "Refreshing",
    "Renewing",
    "Restarting",
    "Relaunching",
    "Reinitiating",
    "Recommencing",
    "Resuming",
    "Continuing",
    "Proceeding",
    "Moving",
    "Advancing",
    "Progressing",
    "Developing",
    "Evolving",
    "Growing",
    "Expanding",
    "Extending",
    "Stretching",
    "Broadening",
    "Widening",
    "Enlarging",
    "Magnifying",
    "Amplifying",
    "Boosting",
    "Enhancing",
    "Improving",
    "Upgrading",
    "Elevating",
    "Raising",
    "Lifting",
    "Increasing",
    "Growing",
    "Building",
    "Constructing",
    "Creating",
    "Making",
    "Producing",
    "Generating",
    "Forming",
    "Shaping",
    "Molding",
    "Fashioning",
    "Crafting",
    "Building",
    "Assembling",
    "Putting",
    "Setting",
    "Placing",
    "Positioning",
    "Locating",
    "Situating",
    "Establishing",
    "Founding",
    "Instituting",
    "Creating",
    "Forming",
    "Organizing",
    "Structuring",
    "Arranging",
    "Ordering",
    "Sorting",
    "Classifying",
    "Categorizing",
    "Grouping",
    "Bunching",
    "Clustering",
    "Collecting",
    "Gathering",
    "Accumulating",
    "Amassing",
    "Assembling",
    "Compiling",
    "Composing",
    "Constituting",
    "Comprising",
    "Embodying",
    "Incorporating",
    "Integrating",
    "Merging",
    "Combining",
    "Joining",
    "Uniting",
    "Connecting",
    "Linking",
    "Attaching",
    "Fastening",
    "Fixing",
    "Securing",
  ],
};
const social = {
  title: homeMetada.title,
  description: homeMetada.description,
  images: [
    {
      url: homeMetada.imgUrl,
      alt: homeMetada.imgAltText,
    },
  ],
  url: homeMetada.url,
};
export const metadata: Metadata = {
  title: homeMetada.title,
  description: homeMetada.description,
  keywords: homeMetada.keywords,
  alternates: {
    canonical: homeMetada.url,
  },
  openGraph: social,
  twitter: social,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function Home() {
  return (
    <>
      <Hero />
      <Features />
      <Video />
      <AboutSectionOne />
      <AboutSectionTwo />
      <Brands />
      {/* <Testimonials /> */}
      {/* <Pricing /> */}
      <Blog />
      <Contact />
      <ScrollUp />
    </>
  );
}
