import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 1,
    name: "Fortinet",
    href: "#",
    image: "/images/brands/Fortinet/fortinet-logo.svg",
    imageLight: "/images/brands/Fortinet/fortinet-logo.svg",
  },
  {
    id: 2,
    name: "AccuKnox",
    href: "#",
    image: "/images/brands/AccuKnox/accuknox-logo.webp",
    imageLight: "/images/brands/AccuKnox/accuknox-logo.webp",
  },
  {
    id: 3,
    name: "WithSecure",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/WithSecure-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/WithSecure-1.png",
  },
  {
    id: 4,
    name: "Acronis",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Acronis.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Acronis.png",
  },
  {
    id: 5,
    name: "Trustwave",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Trustwave-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Trustwave-1.png",
  },
  {
    id: 6,
    name: "Genians",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Genians-3.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Genians-3.png",
  },
  {
    id: 7,
    name: "Jetico",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Jetico.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Jetico.png",
  },
  {
    id: 8,
    name: "KnowBe4",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/knowbe4-logo-black-orange-rgb.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/knowbe4-logo-black-orange-rgb.png",
  },
  {
    id: 9,
    name: "Segura",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/05/67dafd502208e10840444777_Segura-logotype.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/05/67dafd502208e10840444777_Segura-logotype.png",
  },
  {
    id: 10,
    name: "Kiteworks",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Kiteworks-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Kiteworks-1.png",
  },
  {
    id: 11,
    name: "Logsign",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Logsign-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Logsign-1.png",
  },
  {
    id: 12,
    name: "MiniOrange",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/MiniOrange-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/MiniOrange-1.png",
  },
  {
    id: 13,
    name: "Red Sift",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Red-Sift.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Red-Sift.png",
  },
  {
    id: 14,
    name: "Blancco",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Blancco.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Blancco.png",
  },
  {
    id: 15,
    name: "Hexnode",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Hexnode.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Hexnode.png",
  },
  {
    id: 16,
    name: "Syncdog",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Syncdog.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Syncdog.png",
  },
  {
    id: 17,
    name: "Exeon",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/03/Exeon-Logo.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/03/Exeon-Logo.png",
  },
  {
    id: 18,
    name: "Securetrust",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Securetrust.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Securetrust.png",
  },
  {
    id: 19,
    name: "F-Secure",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/F-Secure.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/F-Secure.png",
  },
  {
    id: 20,
    name: "Motadata",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Motadata.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Motadata.png",
  },
  {
    id: 21,
    name: "Somansa",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Somansa-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Somansa-1.png",
  },
  {
    id: 22,
    name: "Codetwo",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Codetwo.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Codetwo.png",
  },
  {
    id: 23,
    name: "Cimcor",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Cimcor-1.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Cimcor-1.png",
  },
  {
    id: 24,
    name: "Black Kite",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Black-Kite.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Black-Kite.png",
  },
  {
    id: 25,
    name: "Randtronics",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Randtronics.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Randtronics.png",
  },
  {
    id: 26,
    name: "NetGain Systems",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/NetGain-Systems.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/NetGain-Systems.png",
  },
  {
    id: 27,
    name: "Sparrow",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/03/CI_Color-1024x180-1-300x53.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/03/CI_Color-1024x180-1-300x53.png",
  },
  {
    id: 28,
    name: "Greenbone",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Logo-Greenbone-H.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2018/08/Logo-Greenbone-H.png",
  },
  {
    id: 29,
    name: "Datalocker",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/01/Datalocker.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2025/01/Datalocker.png",
  },
  {
    id: 30,
    name: "VS Security Products",
    href: "#",
    image: "https://www.rasinfotech-dubai.com/wp-content/uploads/2020/06/VS-securtiy-productd.png",
    imageLight: "https://www.rasinfotech-dubai.com/wp-content/uploads/2020/06/VS-securtiy-productd.png",
  },
];

export default brandsData;
